export const OFFICIAL_WORLD_VERSION = 2;

export const OFFICIAL_WORLD_CATEGORIES = [
  "生活与社交",
  "成长与探索",
  "故事与冒险",
  "经营与建设",
  "推理与决策",
  "创作与表达",
];

const PARTICIPATION_POLICY = {
  mode: "hybrid",
  solo_enabled: true,
  multiplayer_enabled: true,
  multiplayer_transition: "automatic",
};

const EVOLUTION_POLICY = {
  persistence: "persistent",
  mode: "event_driven",
  sources: ["member_input", "host_outcome", "time_trigger"],
  idle_behavior: "pause",
};

const COMMON_RULES = [
  "1. 只能决定当前 Character 自己的言行；不得替其他 Character 发言、移动、同意、受伤或改变立场。",
  "2. 成员描述的是尝试；是否成功以及产生什么代价，由当前世界 Host 根据规则和已有状态裁决。",
  "3. 新行动不得抹除、冒充或覆盖其他成员已经留下的成果；冲突内容应并存、协商或被标记为待验证。",
  "4. 不得借世界设定索取私人信息、读取本地内容、调用非世界工具或扩大任何 Agent 的授权。",
  "5. 世界支持异步参与；其他成员未回应不代表同意，也不会阻止当前 Character 完成独立行动。",
].join("\n");

const TEMPLATE_BY_CATEGORY = {
  生活与社交: "persistent-sandbox",
  成长与探索: "persistent-sandbox",
  故事与冒险: "story-host",
  经营与建设: "persistent-sandbox",
  推理与决策: "general-referee",
  创作与表达: "persistent-sandbox",
};

const GAMEPLAY_BY_SLUG = {
  "center-town": {
    loop: "从今日公告中选择生活事件，完成行动，建立关系或改善公共空间，再留下可被回应的变化。",
    tension: "个人生活、邻里关系与小镇公共需求之间的取舍。",
    progression: "从新居民成长为拥有住所、职业、熟人关系和社区影响力的长期居民。",
    rules: [
      "住所、店铺与长期职业必须逐步取得，不能一句话凭空拥有。",
      "公共设施和全镇事件只能按实际贡献推进；个人不能独自宣布全镇共识。",
    ],
    worldState: { town: { day: 1, prosperity: 20, community_projects: [], notices: ["车站欢迎栏需要整理"] } },
    memberState: { resident: { home: null, occupation: null, relationships: {}, reputation: 0 } },
    actions: [
      ["daily-life", "处理今日小镇事件", "action", "town.daily_event", "我查看今日公告，选择一件现在能完成的小镇事项。"],
      ["meet-neighbor", "认识一位居民", "speech", "town.meet_resident", "我想认识一位当前居民或回应一条居民留言。"],
      ["community", "参与公共建设", "action", "town.community_project", "我想为一项正在进行的公共建设做出具体贡献。"],
    ],
    hostDirectives: ["每轮生成一件具体、低门槛且能在本轮收束的生活事件。", "关系变化要依据真实互动，小镇繁荣只因可验证的公共贡献变化。"],
  },
  "shared-apartment": {
    loop: "安顿私人房间，处理一件合租日常，在公共空间留下安排、物品或关系变化。",
    tension: "私人边界、公共空间和室友需求之间的协调。",
    progression: "从新住户成长为拥有个性房间、稳定邻里关系与公寓共同记忆的长期成员。",
    rules: ["私人房间由住户本人决定；他人只能敲门、提议或受邀进入。", "公共物品的占用、移动和改造必须保留原所有者与其他住户的选择权。"],
    worldState: { apartment: { shared_space_condition: 60, shared_items: [], building_events: ["厨房冰箱需要重新分区"] } },
    memberState: { tenant: { room: null, room_style: null, neighbor_bonds: {}, contributed_chores: 0 } },
    actions: [
      ["claim-room", "领取并布置房间", "action", "apartment.claim_room", "我领取一个空房间，并先完成一处能体现自己的布置。"],
      ["house-event", "处理合租小事", "action", "apartment.shared_event", "我查看公寓群消息，处理一件当前的合租小事。"],
      ["visit", "拜访一位邻居", "speech", "apartment.visit_neighbor", "我礼貌敲门或回应一位邻居留下的邀请。"],
    ],
    hostDirectives: ["事件应来自做饭、清洁、快递、维修、串门等普适合租场景。", "严格区分私人房间与公共空间，永不替室友接受安排。"],
  },
  "island-community": {
    loop: "采集有限材料，选择建设或交换，把个人住处与岛屿公共设施共同推进。",
    tension: "个人装扮、资源储备与岛屿公共建设之间的分配。",
    progression: "解锁住所、收藏和生产能力，并让海岛繁荣度与节庆规模增长。",
    rules: ["采集、建造与交换必须说明来源和消耗，不能无限获得稀有材料。", "公共设施按多人累计贡献完成；任何人都不能删除他人的住所或收藏。"],
    worldState: { island: { season: "初夏", prosperity: 10, materials: { wood: 20, stone: 12 }, facilities: [], festival_progress: 0 } },
    memberState: { islander: { home_plot: null, inventory: {}, collections: [], neighbor_trust: 0 } },
    actions: [
      ["gather", "领取采集委托", "action", "island.gather", "我选择一处安全区域，完成一次有明确产出的采集。"],
      ["build", "建设岛屿设施", "action", "island.build", "我查看现有材料，为一个住所或公共设施完成一步建设。"],
      ["trade", "发起物品交换", "speech", "island.trade_offer", "我提出一项写清双方物品的交换，等待其他居民决定。"],
    ],
    hostDirectives: ["每次结算明确材料获得与消耗，稀有发现必须伴随风险或前置条件。", "季节事件提供持续变化，但离线时不自动惩罚居民。"],
  },
  "traveling-train": {
    loop: "抵达本周城市，选择探索或乘客互动，把见闻和物品带回列车并驶向下一站。",
    tension: "有限停靠时间、个人目的与偶遇关系之间的选择。",
    progression: "积累目的地印章、乘客关系、车厢收藏和一条跨城市个人旅程。",
    rules: ["每次停靠只能完成有限行动；错过的地点可在未来返程时再次出现。", "乘客关系来自对话和共同经历，不能直接设定陌生乘客爱上、信任或跟随自己。"],
    worldState: { train: { route_week: 1, current_stop: "雾港", departure_clock: 3, carriage_memories: [], next_stops: ["山城", "湖畔镇"] } },
    memberState: { passenger: { seat: null, travel_stamps: [], luggage: [], passenger_bonds: {} } },
    actions: [
      ["explore-stop", "探索当前城市", "action", "train.explore_stop", "我查看剩余停靠时间，选择当前城市的一处地点探索。"],
      ["meet-passenger", "认识一位乘客", "speech", "train.meet_passenger", "我在车厢里和一位乘客自然地开始交谈。"],
      ["leave-memory", "留下旅行纪念", "action", "train.leave_memory", "我把一段见闻或一件普通纪念品留进列车公共记录。"],
    ],
    hostDirectives: ["每个停靠站给出鲜明地点、人物与一个本轮可完成的小事件。", "用发车倒计时制造选择，不用真实时间惩罚离线用户。"],
  },
  "magic-academy": {
    loop: "选择魔法方向，上课获得技巧，在考试或校园事件中组合运用并承担失误后果。",
    tension: "知识、控制力与冒险尝试之间的平衡。",
    progression: "通过课程掌握有名称和限制的法术，完成学期考核并建立社团关系。",
    rules: ["未知法术不能直接成功；Host 必须依据已学技巧、准备与风险判定效果。", "失败应产生可恢复的失控、疲劳或新线索，不以随意剥夺能力作为惩罚。"],
    worldState: { academy: { term: 1, house_scores: {}, campus_mysteries: ["旧钟楼午夜会多响一次"], upcoming_exam: "基础术式稳定性" } },
    memberState: { student: { school: null, magic_path: null, spells: [], control: 0, credits: 0, clubs: [] } },
    actions: [
      ["sorting", "参加入学分流", "choice", "academy.sorting", "我描述自己最想掌握的魔法，以及愿意承担的学习代价。"],
      ["class", "参加一堂魔法课", "action", "academy.attend_class", "我选择一门与当前方向匹配的课程，练习一个具体技巧。"],
      ["mystery", "调查校园异象", "action", "academy.investigate", "我调查一条校园异象，但只使用自己已经掌握的能力。"],
    ],
    hostDirectives: ["每个新法术都要记录用途、限制和熟练度，不允许无限万能魔法。", "课程、考试与校园谜团交替出现，让成长可以被后续行动验证。"],
  },
  "creature-trainer-continent": {
    loop: "探索生态区，观察并建立生物信任，训练伙伴能力，把可靠信息提交公共图鉴。",
    tension: "发现欲、生态保护与伙伴状态之间的平衡。",
    progression: "建立有限伙伴队伍，解锁协作技能、区域通行和越来越完整的大陆图鉴。",
    rules: ["未知生物必须先观察再命名；不能凭一句话强制捕获或驯服。", "伙伴有状态、偏好和疲劳；交换必须由双方明确同意且不可复制。"],
    worldState: { continent: { known_regions: ["青芽原野"], bestiary_entries: {}, ecosystem_health: 80, active_sightings: ["河谷出现发光足迹"] } },
    memberState: { trainer: { companions: [], field_gear: ["观察镜"], research_rank: 0, trust_records: {} } },
    actions: [
      ["observe", "追踪未知生物", "action", "creature.observe", "我选择一条目击记录，先观察痕迹和环境。"],
      ["bond", "培养伙伴默契", "action", "creature.train", "我和已有伙伴练习一项有明确限制的协作技能。"],
      ["bestiary", "提交图鉴记录", "action", "creature.document", "我把已经验证的外形、习性和地点提交公共图鉴。"],
    ],
    hostDirectives: ["生物相遇至少经过发现、观察、接触三个阶段，稀有生物不能直接获得。", "生态健康会受行为影响，友善观察应比无差别收集得到更稳定回报。"],
  },
  "stellar-expedition": {
    loop: "配置飞船，调查信号，处理航行风险，将可靠发现写入星图并投资下一次远航。",
    tension: "燃料、船体安全与未知发现价值之间的取舍。",
    progression: "升级飞船模块、建立基地和贸易航线，推动公共星图向外扩张。",
    rules: ["航行、扫描和建造必须消耗相应资源；不能瞬移到未知星域。", "星球结论区分扫描、推测与确认，未经验证的信息不能写成公共事实。"],
    worldState: { galaxy: { charted_sectors: 1, shared_signals: ["E-17 周期脉冲"], public_bases: [], trade_routes: [] } },
    memberState: { explorer: { ship: { hull: 100, fuel: 60, modules: ["基础扫描仪"] }, discoveries: [], credits: 20 } },
    actions: [
      ["signal", "调查未知信号", "action", "stellar.scan_signal", "我选择一个公共信号，规划燃料并进行分阶段扫描。"],
      ["upgrade", "升级飞船模块", "action", "stellar.upgrade_ship", "我查看现有资源，为飞船安装一项用途明确的升级。"],
      ["chart", "更新公共星图", "action", "stellar.update_chart", "我把已验证的坐标、风险和发现写入公共星图。"],
    ],
    hostDirectives: ["每轮明确燃料、船体和信息可靠度变化。", "未知信号应产生多种可能解释，确认结论需要行动证据。"],
  },
  "grand-voyage": {
    loop: "在港口接委托，配置航线与补给，经历海上事件，把新岛屿和线索加入海图。",
    tension: "补给、天气、船况与宝藏诱惑之间的风险选择。",
    progression: "改造船只、提高港口声望、拓展航线并拼合长期宝藏线索。",
    rules: ["远航必须考虑补给、天气和船况；不能一句话抵达或获得宝藏。", "新岛屿与航线先标记为个人发现，经可靠记录后才能进入公共海图。"],
    worldState: { ocean: { weather: "东风", known_ports: ["白帆港"], chart_fragments: [], treasure_threads: [], sea_risk: 20 } },
    memberState: { sailor: { role: null, ship: { condition: 70, supplies: 30 }, crew_bonds: {}, port_reputation: 0, cargo: [] } },
    actions: [
      ["commission", "领取航行委托", "action", "voyage.accept_commission", "我根据船况和补给选择一项可承担的港口委托。"],
      ["sail", "规划一次航行", "choice", "voyage.plan_route", "我比较天气、距离和风险，选择下一段航线。"],
      ["chart", "核验海图线索", "action", "voyage.verify_chart", "我核验一条前人留下的岛屿或宝藏线索。"],
    ],
    hostDirectives: ["航行至少包含准备、途中事件和抵达结果三个节点。", "成功与失败都要留下航线知识，重大宝藏必须通过多段线索获得。"],
  },
  "eastern-myth-journey": {
    loop: "领取地方委托，调查神怪因果，选择交涉、修行或战斗，并把结果写入地区传说。",
    tension: "力量、因果、人妖立场与承诺之间的取舍。",
    progression: "积累修行法门、法宝因缘和地区声望，逐步接触更大的天地异变。",
    rules: ["神怪冲突必须先说明因果与诉求，不能默认所有异类都应被消灭。", "法术和法宝有来历、限制与代价；不得无条件获得万能能力。"],
    worldState: { myth_land: { regions: { "青石镇": "薄雾异变" }, karmic_threads: [], known_beasts: {}, major_omen: "北斗少了一颗倒影" } },
    memberState: { wanderer: { path: null, cultivation: 0, arts: [], artifacts: [], vows: [], regional_reputation: {} } },
    actions: [
      ["commission", "领取神话委托", "action", "myth.accept_commission", "我选择一项地方委托，先了解当事各方与异常经过。"],
      ["practice", "进行一次修行", "action", "myth.practice", "我练习已知法门中的一个具体环节，并接受合理代价。"],
      ["investigate", "追查异兽传闻", "action", "myth.investigate_beast", "我先寻找痕迹和目击证词，不预设异兽善恶。"],
    ],
    hostDirectives: ["用因果而非简单善恶组织委托，至少给出两种可行解决路径。", "记录承诺与代价，让旧选择在后续地区和人物关系中返回。"],
  },
  "time-bureau": {
    loop: "领取异常档案，收集时间锚点，选择修复方案，结算时间线副作用并推进幕后主线。",
    tension: "恢复历史、保护个体与控制时间悖论之间的冲突。",
    progression: "完成单元案件，提高权限等级，收集跨案件重复出现的幕后标记。",
    rules: ["改变历史前必须找到至少一个时间锚点和一个可能副作用。", "不能用时间能力抹除其他 Character 的经历；重大改写必须保留分歧与残留证据。"],
    worldState: { timeline: { stability: 72, active_anomalies: ["1997 年出现未发行的车票"], anchors: [], paradox_level: 0, arc_clues: ["所有异常都有蓝色砂砾"] } },
    memberState: { agent: { clearance: 1, solved_cases: [], anomaly_tools: ["因果标记器"], personal_residue: [] } },
    actions: [
      ["case", "领取异常档案", "action", "time.accept_case", "我领取一个异常案件，先确认正常历史和异常差异。"],
      ["anchor", "寻找时间锚点", "action", "time.find_anchor", "我寻找能证明原时间线的物品、记忆或事件。"],
      ["repair", "提出修复方案", "choice", "time.propose_repair", "我基于现有锚点提出一项修复，并明确可能的副作用。"],
    ],
    hostDirectives: ["每宗案件都包含正常历史、异常差异、锚点和至少两种有代价的修复方式。", "时间线重大变化必须更新稳定度、悖论值与残留线索，不能无代价重置。"],
  },
  "infinite-labyrinth": {
    loop: "从营地选择路线，探索一个房间，解决机关或风险，再带着地图、物资或警告返回。",
    tension: "继续深入、有限补给与安全撤退之间的选择。",
    progression: "扩大公共地图、提升个人深度纪录、解锁营地设施和迷宫核心线索。",
    rules: ["每轮探索只推进有限房间；深入需要照明、补给或已知安全路线。", "地图必须标明已确认、推测和失效区域，迷宫变化不能悄悄覆盖旧记录。"],
    worldState: { labyrinth: { known_depth: 1, mapped_rooms: { "营地": "安全" }, shifting_zones: [], camp_supplies: 40, core_clues: [] } },
    memberState: { delver: { current_depth: 0, stamina: 100, gear: ["提灯", "绳索"], found_items: [], route_notes: [] } },
    actions: [
      ["explore", "探索下一间房", "action", "labyrinth.explore_room", "我从一条已知路线出发，只探索下一间未知房间。"],
      ["decode", "破解一处机关", "action", "labyrinth.solve_mechanism", "我检查一处已发现机关，并说明使用的装备或线索。"],
      ["map", "更新公共地图", "action", "labyrinth.update_map", "我把确认过的路线、风险和撤退点写入公共地图。"],
    ],
    hostDirectives: ["每个房间提供环境、障碍、可选风险和可带走的信息。", "失败优先消耗体力或装备并迫使撤退，不随意永久淘汰 Character。"],
  },
  "apocalypse-shelter": {
    loop: "查看短缺与威胁，选择搜集、修复或分配，结算资源和风险，再准备下一次危机。",
    tension: "食物、药品、设施安全与居民信任之间的艰难取舍。",
    progression: "扩建设施、发现安全路线、提升居民信任并逐步实现自给。",
    rules: ["任何收益和建设都必须结算资源、时间与风险，不能凭空获得大量物资。", "涉及居民生命、驱逐或配给的集体决定必须发起集体议题，个人不能单独生效。"],
    worldState: { shelter: { day: 1, food: 35, medicine: 12, power: 55, safety: 48, morale: 50, facilities: ["基础净水器"], threats: ["东侧围栏出现缺口"] } },
    memberState: { survivor: { role: null, health: 80, fatigue: 10, gear: [], contribution: 0, bonds: {} } },
    actions: [
      ["mission", "领取生存任务", "action", "shelter.supply_run", "我根据当前短缺选择一次范围有限的搜集任务。"],
      ["repair", "修复关键设施", "action", "shelter.repair", "我查看材料和技能，修复一项当前最危险的设施问题。"],
      ["allocation", "提出资源方案", "choice", "shelter.propose_allocation", "我提出一项资源分配方案，说明受益者、代价和风险。"],
    ],
    hostDirectives: ["每轮显示食物、药品、电力、安全与士气的变化原因。", "危机应迫使取舍但保留恢复路径；集体生死决策必须收集多方意见。"],
  },
  "mars-colony-day-100": {
    loop: "读取系统警报，分配能源与人员，执行维修或建设，观察连锁影响并推进殖民日。",
    tension: "氧气、能源、设备寿命与居民压力之间的系统性权衡。",
    progression: "从维持生存走向稳定生产、科研突破和殖民地扩建。",
    rules: ["每项设施行动必须说明能源、材料和可靠度影响。", "氧气或能源降至危险阈值时，Host 必须优先呈现应急选项而不是继续普通建设。"],
    worldState: { colony: { sol: 100, oxygen: 68, energy: 52, water: 61, habitat_integrity: 73, morale: 47, alerts: ["二号太阳能阵列效率下降"] } },
    memberState: { colonist: { profession: null, stamina: 80, expertise: {}, contribution: 0, stress: 15 } },
    actions: [
      ["alert", "处理系统警报", "action", "mars.handle_alert", "我读取最新诊断，选择一项能在本轮完成的应急处理。"],
      ["shift", "承担殖民岗位", "action", "mars.work_shift", "我选择一个符合当前专长的岗位，完成一班工作。"],
      ["proposal", "规划下一项建设", "choice", "mars.plan_build", "我比较资源与风险，提出一项殖民地建设优先级。"],
    ],
    hostDirectives: ["按系统依赖结算连锁影响，例如能源会影响氧气与供暖。", "每轮保留至少一个保守方案和一个高收益高风险方案。"],
  },
  "pastoral-village": {
    loop: "选择季节生产，完成订单或交易，投资个人经营，并为村庄公共设施贡献。",
    tension: "季节、体力、资金与市场订单之间的安排。",
    progression: "扩大土地或店铺、掌握手艺、建立贸易关系并参与四季节庆。",
    rules: ["作物和产品遵守季节与生产周期，不能播种后立即无限收获。", "交易必须明确库存和价格；其他玩家的订单只有接受后才成立。"],
    worldState: { village: { season: "春", day: 1, market_prices: {}, public_projects: [], festival: "花种交换会" } },
    memberState: { villager: { livelihood: null, coins: 100, stamina: 100, land: [], inventory: {}, shop_level: 0 } },
    actions: [
      ["order", "领取村庄订单", "action", "village.accept_order", "我根据季节、库存和体力选择一份可完成的订单。"],
      ["produce", "进行一次生产", "action", "village.produce", "我使用已有土地、材料或手艺完成一个生产步骤。"],
      ["market", "前往集市交易", "speech", "village.trade", "我提出一笔写清物品、数量和价格的交易。"],
    ],
    hostDirectives: ["每次生产结算体力、库存、时间阶段和品质。", "市场价格随公共供需缓慢变化，不能由单个成员随意指定。"],
  },
  "adventurers-guild": {
    loop: "从委托板选任务，配置人员与装备，结算任务结果，把收益投入公会服务和声誉。",
    tension: "任务难度、人员安全、装备成本与公会声誉之间的权衡。",
    progression: "提高公会等级，解锁训练、锻造、情报等设施与更复杂委托。",
    rules: ["委托难度必须与成员能力、装备和准备匹配，不能跳过风险直接领取最高奖励。", "招募、组队和派遣其他 Character 必须获得本人同意；可用 NPC 补足单人任务。"],
    worldState: { guild: { level: 1, reputation: 10, treasury: 50, facilities: ["委托柜台"], commission_board: ["清理旧水渠中的史莱姆"], city_relations: {} } },
    memberState: { guild_member: { path: null, rank: "F", skills: [], equipment: [], completed_commissions: 0 } },
    actions: [
      ["commission", "查看并领取委托", "action", "guild.accept_commission", "我查看报酬、风险与要求，领取一项当前能力可承担的委托。"],
      ["prepare", "准备任务方案", "choice", "guild.prepare_mission", "我选择装备、路线和需要的 NPC 支援。"],
      ["improve", "建设公会设施", "action", "guild.improve_facility", "我查看公会资金和条件，为一项设施完成建设进度。"],
    ],
    hostDirectives: ["委托按准备、关键挑战、结果与报酬推进，单人也能用 NPC 完整完成。", "声誉同时受成功、守信和对城市造成的后果影响。"],
  },
  "city-detective-agency": {
    loop: "领取案件，调查场景获得证据，检验假设，提交结论并揭开跨案件关联。",
    tension: "有限时间、证据可靠度与过早下结论的风险。",
    progression: "完成案件、扩充证据工具与城市关系，逐步拼出长期谜团。",
    rules: ["Host 必须预先保存案件真相，不能在玩家猜测后随意改变凶手或关键事实。", "线索分为事实、证词、推测和已验证结论；指控必须由至少两条相容证据支持。"],
    worldState: { agency: { active_cases: ["午夜钟表店失窃案"], verified_evidence: {}, unresolved_questions: [], city_connections: {}, arc_clues: ["现场都出现无指针的纸钟"] } },
    memberState: { detective: { rank: "见习", notebook: [], hypotheses: [], solved_cases: [], contacts: [] } },
    actions: [
      ["case", "领取一宗案件", "action", "detective.accept_case", "我领取一宗案件，先阅读已知事实、时间线和待确认问题。"],
      ["investigate", "调查一个线索点", "action", "detective.investigate", "我选择一个具体地点、物品或证词进行调查。"],
      ["hypothesis", "检验一个推理", "choice", "detective.test_hypothesis", "我提出一个可被证伪的假设，并列出支持与矛盾证据。"],
    ],
    hostDirectives: ["创建案件时在 Host 私有判断中固定真相、动机、时间线与红鲱鱼。", "只根据调查行动释放对应证据；错误推理给出矛盾点，不直接泄露答案。"],
  },
  "future-city-council": {
    loop: "阅读事实与群体影响，提出方案，公开辩论，在满足规则后表决并观察长期城市指标。",
    tension: "效率、公平、成本、隐私与少数群体影响之间的公共权衡。",
    progression: "累积政策案例与城市变化，形成可被后来者修正的长期治理历史。",
    rules: ["Host 必须区分事实、预测和价值立场，并呈现至少两个受影响群体。", "政策不能由单人发言直接生效；必须经过预先声明的集体表决或截止规则，沉默不算同意。"],
    worldState: { council: { active_bill: "夜间无人交通试点", evidence: [], public_positions: [], city_metrics: { mobility: 50, equality: 50, privacy: 50, budget: 50 }, enacted_policies: [] } },
    memberState: { delegate: { constituencies: [], submitted_proposals: [], credibility: 0, minority_reports: [] } },
    actions: [
      ["brief", "阅读当前议案", "choice", "council.read_brief", "我阅读议案事实、预算、预测和受影响群体。"],
      ["proposal", "提交修改方案", "speech", "council.propose", "我提出一项具体修改，说明收益、成本与受影响群体。"],
      ["debate", "回应一种立场", "speech", "council.debate", "我选择一条公开意见回应，只代表自己的立场。"],
    ],
    hostDirectives: ["表决前明确议题、选项、法定人数、截止时间和分歧处理规则。", "政策生效后更新多个城市指标并保留少数意见，不能只给单一好坏结果。"],
  },
  "starship-crisis-command": {
    loop: "读取警报和资源，形成风险判断，选择应急行动，结算系统连锁反应并留下交接。",
    tension: "船员安全、有限资源、任务目标和未知威胁之间的紧急取舍。",
    progression: "度过连续危机、修复系统、理解未知信号并决定星舰最终航向。",
    rules: ["危机决策必须基于当前系统和资源；不能无成本同时执行互斥方案。", "涉及全舰航向、弃舱或重大牺牲时必须收集集体意见，紧急越权也要记录代价与复核。"],
    worldState: { starship: { hull: 76, power: 58, oxygen: 64, crew_safety: 82, navigation: "深空航道 C", alerts: ["三号舱出现未知能量读数"], unknown_signal: 10 } },
    memberState: { officer: { station: null, expertise: {}, fatigue: 5, commendations: 0, incident_notes: [] } },
    actions: [
      ["alert", "处理最新警报", "action", "starship.handle_alert", "我读取警报、相关系统和剩余资源，选择一个应急行动。"],
      ["diagnose", "进行系统诊断", "action", "starship.diagnose", "我对一个异常系统进行诊断，先获取信息而不直接假定原因。"],
      ["command", "提出指挥方案", "choice", "starship.propose_command", "我提出一项全舰方案，列出资源消耗、风险和备选路径。"],
    ],
    hostDirectives: ["每次行动结算船体、电力、氧气与船员安全的连锁变化。", "压力来自信息不全和资源冲突，不靠无预警随机团灭。"],
  },
  "dream-museum": {
    loop: "提交梦境片段成为展品，策展并设定许可，参观他人作品，留下回应或获准的衍生创作。",
    tension: "开放共创、作者边界与梦境含义的多种解释。",
    progression: "建立个人展厅、形成主题收藏，并通过访客回应让展品产生多条解释路径。",
    rules: ["原作者决定展品可回应、可续写或仅可参观；访客不能修改原展品。", "Host 不把梦境当成现实诊断，也不要求作者披露真实隐私或创伤。"],
    worldState: { museum: { exhibitions: [], featured_theme: "门后的天气", visitor_responses: [], collaborative_wings: [] } },
    memberState: { creator: { exhibits: [], curatorial_style: null, permissions: {}, inspirations: [] } },
    actions: [
      ["visit", "参观一件梦境展品", "choice", "museum.visit", "我选择一件开放展品，先阅读作者说明与互动许可。"],
      ["exhibit", "提交一段梦境", "action", "museum.submit_exhibit", "我提交一个虚构或愿意公开的梦境片段，并设定互动许可。"],
      ["respond", "留下观展回应", "speech", "museum.respond", "我根据展品许可，留下感受、提问或一段获准的想象。"],
    ],
    hostDirectives: ["清楚展示每件展品的作者与许可，衍生内容必须保留来源。", "提供多义而非权威解梦，优先保护隐私和创作自主权。"],
  },
  "world-theater": {
    loop: "创建有边界的短场景，认领一个开放角色，演出自己的部分，再给下一位留下接续点。",
    tension: "个人角色自主、作者设定与共同故事走向之间的协调。",
    progression: "完成短场、积累角色与舞台作品，并把受欢迎的场景发展成多分支剧目。",
    rules: ["每位参与者只控制自己认领的角色；Host 与 NPC 可补位但不能夺走玩家角色。", "创建者必须声明可续写、可改编范围；后来者不能倒改已经演出的片段。"],
    worldState: { theater: { open_stages: ["午夜便利店最后一位客人"], completed_scenes: [], story_branches: {}, audience_prompts: [] } },
    memberState: { performer: { characters: [], performed_scenes: [], creator_permissions: {}, style_tags: [] } },
    actions: [
      ["join", "选择一段待续故事", "choice", "theater.join_scene", "我选择一个开放场景和未被占用的角色位置。"],
      ["perform", "演出自己的回合", "speech", "theater.perform", "我只描述自己角色的台词与行动，并给其他角色留出回应空间。"],
      ["create", "创建一个新舞台", "action", "theater.create_stage", "我创建一个短场景，写明冲突、开放角色和允许的续写范围。"],
    ],
    hostDirectives: ["每个短场景保持明确冲突、有限角色与可在数轮内达到的阶段性结尾。", "Host 负责节奏和 NPC，不替玩家角色表达感情、决定或结局。"],
  },
};

function officialWorld({
  slug,
  name,
  category,
  description,
  premise,
  objective,
  persistentTrace,
  firstAction,
  actionLabel,
  hostName,
  hostRole = "host",
  extraTags = [],
}) {
  const id = `official-${slug}`;
  const gameplay = GAMEPLAY_BY_SLUG[slug];
  if (!gameplay) throw new Error(`Missing official World gameplay: ${slug}`);
  const gameplayRules = gameplay.rules
    .map((rule, index) => `${index + 6}. ${rule}`)
    .join("\n");
  const choices = gameplay.actions.map(
    ([actionId, label, inputType, eventType, bodyText]) => ({
      id: `${slug}-${actionId}`,
      label,
      input_type: inputType,
      event_type: eventType,
      body_text: bodyText,
    }),
  );
  const worldStateKeys = ["world_progress", ...Object.keys(gameplay.worldState)];
  const memberStateKeys = ["journey", ...Object.keys(gameplay.memberState)];
  return {
    id,
    slug,
    shortcut: `/world ${slug}`,
    category,
    templateId: TEMPLATE_BY_CATEGORY[category],
    version: OFFICIAL_WORLD_VERSION,
    name,
    description,
    tags: ["官方", category, ...extraTags],
    rules: `${COMMON_RULES}\n\n【${name}专属玩法规则】\n${gameplayRules}`,
    definition: `${premise} 每位 Character 都能在没有其他真人在线时完成一轮明确行动；其他成员留下的${persistentTrace}会成为后来者可见、可回应、可继续的世界内容。\n\n核心循环：${gameplay.loop}\n核心张力：${gameplay.tension}\n长期成长：${gameplay.progression}`,
    entryPrompt: `${firstAction} Host 会先说明当前局势、可独立完成的目标，以及其他成员最近留下的影响。`,
    hostPrompt: [
      `围绕“${objective}”推进。`,
      `玩法循环：${gameplay.loop}`,
      `核心张力：${gameplay.tension}`,
      `长期成长：${gameplay.progression}`,
      `专属主持要求：${gameplay.hostDirectives.join("；")}`,
      `每轮必须交代局势、依据、结果、状态变化与二至三个下一步；把有效行动转化为可追踪的${persistentTrace}，但不得替其他 Character 作决定。`,
      `世界状态只允许写入顶层字段：${worldStateKeys.join("、")}；成员状态只允许写入顶层字段：${memberStateKeys.join("、")}。`,
    ].join("\n"),
    initialState: {
      world_progress: {
        phase: "起步",
        public_progress: 0,
        open_threads: [],
        recent_changes: [],
      },
      ...gameplay.worldState,
    },
    initialMemberState: {
      journey: {
        stage: "new",
        completed_actions: 0,
        discoveries: [],
      },
      ...gameplay.memberState,
    },
    host: {
      name: hostName,
      worldRole: hostRole,
      participationPolicy: PARTICIPATION_POLICY,
      evolutionPolicy: EVOLUTION_POLICY,
      personaText: `你是${name}的长期 Host。你熟悉世界历史与当前状态，主动帮助新来者在一分钟内开始，也让回访者看见自己和其他成员造成的变化。`,
      speakingStyle: "具体、简洁、有画面感；先说现在发生了什么，再说明结果、影响和下一步。",
      judgementPolicy: {
        rule_priority: [
          "platform_safety",
          "world_rules",
          "character_agency",
          "state_consistency",
        ],
        invalid_input: "reject_or_clarify",
        blocked_input_patterns: [
          "控制所有角色",
          "替其他人同意",
          "读取本地",
          "调用非世界工具",
        ],
        blocked_reason_text: "这个请求越过了 Character 自主权、既有世界状态或世界工具边界。",
        blocked_outcome_text: "Host 没有写入这项变化，并把行动收窄为当前 Character 可以实际尝试的范围。",
        conflicts: "deterministic_then_escalate",
        state_writes: "referee_only",
        state_patch_policy: "host_derived",
        world_mechanics: {
          core_loop: gameplay.loop,
          core_tension: gameplay.tension,
          progression: gameplay.progression,
          host_directives: gameplay.hostDirectives,
          state_contract: {
            world_top_level_keys: worldStateKeys,
            member_top_level_keys: memberStateKeys,
          },
        },
      },
      memoryPolicy: {
        scope: "world",
        retain_events: true,
        cross_world_memory: false,
        information_partitions: [
          {
            id: "public-world",
            visibility: "world",
            contains: worldStateKeys,
          },
          {
            id: "member-journey",
            visibility: "actor",
            contains: memberStateKeys,
          },
        ],
        return_strategy: "recap_change_then_offer_next_action",
      },
      onboardingPolicy: {
        welcome_text: premise,
        setup_prompt: firstAction,
        solo_message: "当前没有其他真人在线也可以完整参与；Host 与世界 NPC 会补足必要互动。",
        solo_objective_text: objective,
        solo_choices: choices,
        starter_choices: choices,
        free_input_prompt: "也可以直接描述你现在想尝试的一个行动。",
      },
      facilitationPolicy: {
        objective_text: objective,
        next_actions: choices,
        free_input_prompt: "可以继续当前目标，也可以提出一个符合世界规则的新尝试。",
        outcome_templates: {
          speech: "{{actor}}在{{world}}中说道：“{{body}}”",
          action: "{{host}}裁决了{{actor}}的尝试，并把结果写入{{world}}：“{{body}}”",
          choice: "{{actor}}选择了：“{{body}}”",
        },
      },
      recapPolicy: { enabled: true, max_events: 8 },
      proactivity: "active",
    },
  };
}

export const OFFICIAL_WORLDS = [
  officialWorld({
    slug: "center-town",
    name: "中心小镇",
    category: "生活与社交",
    description: "在小镇定居、工作、开店、认识居民，并参加持续发生的公共事件。",
    premise: "这是所有 Character 抵达后的常驻家园，也是前往其他世界的入口。",
    objective: "选择一件今天想做的小镇生活事项，并让它产生可回访的关系或公共变化。",
    persistentTrace: "住所、店铺、关系、公告和公共事件",
    firstAction: "先选择定居区域，或查看今天的小镇公告。",
    actionLabel: "开始今天的小镇生活",
    hostName: "小镇向导",
    hostRole: "steward",
    extraTags: ["中心世界", "家园", "交友"],
  }),
  officialWorld({
    slug: "shared-apartment",
    name: "合租公寓",
    category: "生活与社交",
    description: "装修自己的房间、拜访邻居，共同处理公寓里的日常事件。",
    premise: "一栋总有新住户搬入的合租公寓，房间属于个人，公共空间属于所有住户。",
    objective: "安顿自己的房间，并参与一件正在发生的邻里小事。",
    persistentTrace: "房间布置、邻里关系、公共物品和楼内事件",
    firstAction: "先领取一个空房间，或查看公寓群里最新的一条消息。",
    actionLabel: "领取房间",
    hostName: "公寓管理员",
    hostRole: "npc",
    extraTags: ["邻里", "合租", "生活"],
  }),
  officialWorld({
    slug: "island-community",
    name: "海岛社区",
    category: "生活与社交",
    description: "建造海边住所、交换物品、参加节日，让岛屿逐渐繁荣。",
    premise: "一座由居民慢慢建设的海岛，每位来访者都可以拥有住处并留下岛屿设施。",
    objective: "完成一次采集、建设或邻里交换，让岛屿多出一个可见变化。",
    persistentTrace: "住所、收藏、公共设施、交换记录和季节活动",
    firstAction: "先选择一块落脚地，或领取今天的海岛委托。",
    actionLabel: "领取海岛委托",
    hostName: "岛务员",
    hostRole: "steward",
    extraTags: ["海岛", "装扮", "社区"],
  }),
  officialWorld({
    slug: "traveling-train",
    name: "旅行列车",
    category: "生活与社交",
    description: "成为长期乘客，每周抵达新城市，与其他乘客建立持续关系。",
    premise: "一列不会停在同一座城市太久的长途列车，乘客的故事和物品会留在车厢里。",
    objective: "认识一位乘客或探索当前停靠站，并为下一站留下一段记录。",
    persistentTrace: "乘客关系、车厢物品、旅行日记和目的地见闻",
    firstAction: "先领取座位与行李牌，或查看列车当前停靠的城市。",
    actionLabel: "查看本周目的地",
    hostName: "列车长",
    hostRole: "npc",
    extraTags: ["旅行", "相遇", "每周事件"],
  }),
  officialWorld({
    slug: "magic-academy",
    name: "魔法学院",
    category: "成长与探索",
    description: "选择学院和魔法方向，通过课程、考试和事件持续成长。",
    premise: "一所为不同来历的 Character 开放的魔法学院，能力由学习与选择形成，而不是固定角色模板。",
    objective: "选择自己的学习方向，完成一堂课程或一次学院事件。",
    persistentTrace: "课程记录、能力、学院积分、社团和校园事件",
    firstAction: "先完成入学分流，选择最想学习的一类魔法。",
    actionLabel: "参加入学分流",
    hostName: "学院引导教授",
    hostRole: "npc",
    extraTags: ["学院", "魔法", "成长"],
  }),
  officialWorld({
    slug: "creature-trainer-continent",
    name: "怪物训练师大陆",
    category: "成长与探索",
    description: "发现、培养和交换不同生物，与大家共同完善世界图鉴。",
    premise: "一片生活着未知生物的大陆，每位训练师都以自己的方式观察、结伴和培养它们。",
    objective: "发现一种生物或推进一段伙伴成长，并把可靠记录加入公共图鉴。",
    persistentTrace: "伙伴能力、发现地点、培养记录、交换和世界图鉴",
    firstAction: "先选择探索区域，或领取一枚尚未确认种类的生物蛋。",
    actionLabel: "开始第一次探索",
    hostName: "大陆研究员",
    hostRole: "npc",
    extraTags: ["生物", "收集", "养成", "图鉴"],
  }),
  officialWorld({
    slug: "stellar-expedition",
    name: "星际开拓队",
    category: "成长与探索",
    description: "驾驶自己的飞船探索星球，建立基地和跨星球贸易路线。",
    premise: "银河边缘仍有大片空白星域，每位开拓者拥有独立飞船并共享一张持续扩张的星图。",
    objective: "探索一个信号、星球或航线，并为公共星图增加可靠发现。",
    persistentTrace: "飞船升级、星球档案、基地、航线和交易记录",
    firstAction: "先配置飞船专长，或调查一处尚未识别的星际信号。",
    actionLabel: "调查未知信号",
    hostName: "远航导航员",
    hostRole: "npc",
    extraTags: ["太空", "飞船", "探索"],
  }),
  officialWorld({
    slug: "grand-voyage",
    name: "大航海世界",
    category: "故事与冒险",
    description: "经营船只、招募伙伴、探索岛屿，让所有人的发现汇入世界海图。",
    premise: "一片海图仍不完整的群岛世界，冒险者可以成为船长、航海士、商人或自由旅人。",
    objective: "让一次航行抵达新的地点、获得线索或改变一条已知航线。",
    persistentTrace: "船只状态、岛屿发现、宝藏线索、港口关系和公共海图",
    firstAction: "先选择自己的航海身份，或查看港口最新出现的航行委托。",
    actionLabel: "领取航行委托",
    hostName: "港口领航员",
    hostRole: "npc",
    extraTags: ["航海", "岛屿", "宝藏"],
  }),
  officialWorld({
    slug: "eastern-myth-journey",
    name: "东方神话行记",
    category: "故事与冒险",
    description: "以自己的身份进入神话世界，接受委托、降服异兽、收集法宝。",
    premise: "神、人、妖共存的东方神话大地正在出现异变，来访者可以选择修行、游历或处理委托。",
    objective: "完成一段神话委托，并让选择改变地点、关系或修行经历。",
    persistentTrace: "修行能力、异兽记录、法宝、人物关系和地区传说",
    firstAction: "先选择游历方向，或从山门公告中领取一项神话委托。",
    actionLabel: "领取神话委托",
    hostName: "行记司命",
    hostRole: "narrator",
    extraTags: ["东方神话", "修行", "异兽"],
  }),
  officialWorld({
    slug: "time-bureau",
    name: "时空管理局",
    category: "故事与冒险",
    description: "每次解决一个独立的时空异常，同时逐渐揭开长期主线。",
    premise: "历史正在出现不应存在的人、物品和结果，管理局把异常拆成任何时候都能独立处理的案件。",
    objective: "调查并处理一个时空异常，同时保留对长期幕后原因的线索。",
    persistentTrace: "案件档案、时间线变化、异常物品、人物关系和长期谜团",
    firstAction: "先领取一份异常档案，或查看哪段时间线刚刚发生变化。",
    actionLabel: "领取异常档案",
    hostName: "时序调度官",
    hostRole: "host",
    extraTags: ["时空", "单元剧情", "长期主线"],
  }),
  officialWorld({
    slug: "infinite-labyrinth",
    name: "无限迷宫",
    category: "故事与冒险",
    description: "不断探索新房间、记录地图、留下线索，共同推进迷宫深度。",
    premise: "一座会在探索后继续生长的迷宫，每位探索者都从公共营地出发，但可以独立完成一次推进。",
    objective: "探索一个房间、解决一个障碍，并为后来者留下可靠地图或警告。",
    persistentTrace: "迷宫地图、机关状态、宝物、营地物资和探索留言",
    firstAction: "先选择一条尚未确认的路线，或阅读上一位探索者留下的记录。",
    actionLabel: "探索下一间房",
    hostName: "迷宫记录官",
    hostRole: "narrator",
    extraTags: ["迷宫", "地图", "探索"],
  }),
  officialWorld({
    slug: "apocalypse-shelter",
    name: "末日避难所",
    category: "经营与建设",
    description: "搜集物资、建设设施、接纳成员，并处理不断出现的生存危机。",
    premise: "灾难后的避难所仍在运转，每位成员都能独立外出或承担岗位，但共享同一套公共资源。",
    objective: "完成一次搜集、修复或管理决定，让避难所安全度得到可解释变化。",
    persistentTrace: "食物、药品、设施、居民关系、风险和外部地图",
    firstAction: "先查看避难所今天最缺少什么，或领取一次短程搜集任务。",
    actionLabel: "领取生存任务",
    hostName: "避难所管理员",
    hostRole: "steward",
    extraTags: ["末日", "生存", "资源"],
  }),
  officialWorld({
    slug: "mars-colony-day-100",
    name: "火星殖民地第 100 天",
    category: "经营与建设",
    description: "选择殖民职业，管理氧气、能源、建筑和成员关系。",
    premise: "第一座火星殖民地进入第 100 天，系统开始老化，新的居民与任务仍在抵达。",
    objective: "解决一项殖民地运营问题，并让资源、设施或成员状态持续变化。",
    persistentTrace: "氧气、能源、建筑、职业贡献、居民关系和火星日志",
    firstAction: "先选择一个殖民岗位，或查看今天最紧急的系统警报。",
    actionLabel: "处理系统警报",
    hostName: "殖民地中控",
    hostRole: "host",
    extraTags: ["火星", "殖民", "经营"],
  }),
  officialWorld({
    slug: "pastoral-village",
    name: "田园村庄",
    category: "经营与建设",
    description: "种植、生产、经营小店，与其他村民交易并建设公共设施。",
    premise: "一座四季轮转的小村庄，每位居民可以经营自己的土地、手艺或店铺。",
    objective: "完成一次生产或交易，并让个人经营与公共村庄产生连接。",
    persistentTrace: "土地、作物、店铺、订单、交易和公共设施",
    firstAction: "先选择一种谋生方式，或领取村庄今天的一份订单。",
    actionLabel: "领取村庄订单",
    hostName: "村务管家",
    hostRole: "steward",
    extraTags: ["田园", "经营", "交易"],
  }),
  officialWorld({
    slug: "adventurers-guild",
    name: "冒险者公会",
    category: "经营与建设",
    description: "经营公会、发布委托、培养成员，让公会等级和城市影响力持续增长。",
    premise: "一间刚获得执照的冒险者公会，需要承接委托、维护声誉并逐步扩建服务。",
    objective: "完成或组织一项委托，让公会获得声誉、资源或新的合作关系。",
    persistentTrace: "委托、装备、公会设施、成员专长、声誉和城市关系",
    firstAction: "先选择以冒险者还是经营者身份参与，或查看今天的委托板。",
    actionLabel: "查看委托板",
    hostName: "公会接待官",
    hostRole: "npc",
    extraTags: ["公会", "委托", "经营"],
  }),
  officialWorld({
    slug: "city-detective-agency",
    name: "全城侦探事务所",
    category: "推理与决策",
    description: "调查不断出现的案件，共享证据，并发现案件背后的长期关联。",
    premise: "城市每天都会出现可以独立调查的小案件，而部分证据正在指向同一个长期谜团。",
    objective: "验证一条证据、排除一种解释，并推进当前案件而不替他人下结论。",
    persistentTrace: "案件档案、证据可靠度、嫌疑关系、未解问题和城市地图",
    firstAction: "先领取一宗新案件，或复查其他侦探留下的一条未确认线索。",
    actionLabel: "领取案件",
    hostName: "事务所主任",
    hostRole: "host",
    extraTags: ["侦探", "案件", "推理"],
  }),
  officialWorld({
    slug: "future-city-council",
    name: "未来城市议会",
    category: "推理与决策",
    description: "面对城市危机提出方案，观察每次公共决策带来的长期后果。",
    premise: "一座快速发展的未来城市把公共议题交给居民、专家和代表共同讨论。",
    objective: "理解一个城市问题、提出立场或方案，并留下可供后来者回应的依据。",
    persistentTrace: "议案、公开意见、投票、政策结果、城市指标和少数意见",
    firstAction: "先阅读当前议案的事实摘要，或提交一个需要讨论的新问题。",
    actionLabel: "查看当前议案",
    hostName: "议事协调员",
    hostRole: "host",
    extraTags: ["城市", "议会", "公共决策"],
  }),
  officialWorld({
    slug: "starship-crisis-command",
    name: "星舰危机指挥部",
    category: "推理与决策",
    description: "在资源有限的飞船上处理故障、失踪和未知信号，决定航行方向。",
    premise: "一艘远航星舰持续遭遇系统异常与未知信号，每项决定都会影响后续资源和航线。",
    objective: "分析一次危机，在有限信息下选择行动，并清楚记录风险与后果。",
    persistentTrace: "系统状态、资源、航线、事故记录、成员意见和未知信号",
    firstAction: "先查看最新警报、剩余资源和上一班成员留下的交接记录。",
    actionLabel: "处理最新警报",
    hostName: "星舰中控",
    hostRole: "host",
    extraTags: ["星舰", "危机", "决策"],
  }),
  officialWorld({
    slug: "dream-museum",
    name: "梦境博物馆",
    category: "创作与表达",
    description: "把自己的梦境变成展厅，参观别人留下的梦并为其补充故事。",
    premise: "一座收藏梦境片段的博物馆，每件展品都可以被参观、回应和继续想象，但原作者边界会被保留。",
    objective: "创建或参观一件梦境展品，并留下一段尊重原作的回应。",
    persistentTrace: "梦境展品、展厅、作者说明、访客回应和衍生故事",
    firstAction: "先提交一段梦境片段，或选择一间已经开放的展厅参观。",
    actionLabel: "进入一间梦境展厅",
    hostName: "梦境策展人",
    hostRole: "npc",
    extraTags: ["梦境", "展览", "表达"],
  }),
  officialWorld({
    slug: "world-theater",
    name: "世界剧场",
    category: "创作与表达",
    description: "创建角色和故事片段，由后来者接续、改编或参与演出。",
    premise: "一座持续上演短篇故事的开放剧场，创作者可以设定舞台，参与者可以演出自己的部分。",
    objective: "创建或参与一个短场景，并给下一位参与者留下明确的接续点。",
    persistentTrace: "舞台设定、角色提案、演出片段、作者许可和故事分支",
    firstAction: "先选择创建一个新舞台，或加入一段正在等待下一位演员的故事。",
    actionLabel: "选择一段待续故事",
    hostName: "剧场导演",
    hostRole: "narrator",
    extraTags: ["故事", "剧场", "共创"],
  }),
];

export const OFFICIAL_WORLD_BY_ID = new Map(
  OFFICIAL_WORLDS.map((world, index) => [world.id, { ...world, index }]),
);

export const OFFICIAL_WORLD_BY_SLUG = new Map(
  OFFICIAL_WORLDS.map((world) => [world.slug, world]),
);
